In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [39]:
path='Fifa_world_cup_matches.csv'
df = pd.read_csv(path)
df.head()

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361

In [40]:
df.drop(["team1","team2","date","hour","category"], axis = 1, inplace=True)

In [41]:
df['possession team1'] = df['possession team1'].map(lambda x: x.lstrip('+-').rstrip('%'))
df['possession team2'] = df['possession team2'].map(lambda x: x.lstrip('+-').rstrip('%'))
df['possession in contest'] = df['possession in contest'].map(lambda x: x.lstrip('+-').rstrip('%'))
df

,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,42,50,8,0,2,5,6,2,0,0,...,0,1,6,5,0,0,52,72,256,279
1,72,19,9,6,2,13,8,2,6,6,...,0,1,8,13,0,0,63,72,139,416
2,44,45,11,0,2,14,9,2,0,0,...,0,0,9,15,0,0,63,73,263,251
3,51,39,10,1,1,6,7,1,1,1,...,0,1,7,7,0,0,81,72,242,292
4,64,24,12,1,2,14,3,2,1,1,...,1,0,4,14,0,0,65,80,163,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,54,36,10,1,2,14,9,2,1,1,...,1,0,9,15,0,0,49,54,193,308
60,34,54,12,3,0,10,12,0,3,3,...,1,0,12,10,0,0,85,63,321,260
61,34,55,11,2,0,14,13,0,2,2,...,0,0,13,14,0,0,72,47,328,218
62,45,45,10,2,1,14,7,1,2,2,...,0,0,7,14,0,0,75,72,288,277
63,46,40,14,3,3,21,10,3,3,3,...,1,2,11,21,0,0,87,104,280,409

In [42]:
train_set, test_set = train_test_split(df, test_size=0.2, random_state = 42)
train_set.head()

,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
13,49,38,13,0,0,10,6,0,0,0,...,0,0,6,10,0,0,65,54,240,231
34,33,58,10,0,3,7,17,3,0,0,...,0,0,17,8,0,0,49,56,328,167
50,48,42,10,3,1,16,11,1,3,3,...,0,1,11,16,0,0,71,64,220,297
3,51,39,10,1,1,6,7,1,1,1,...,0,1,7,7,0,0,81,72,242,292
17,42,48,10,1,3,10,12,3,1,1,...,0,0,12,11,0,0,67,67,308,232

In [43]:
y_train = train_set["number of goals team1"].copy()
x_train = train_set.drop("number of goals team1",axis=1)

In [44]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [45]:
train_preds = lr.predict(x_train)
mse = mean_squared_error(train_preds,y_train)
print(np.sqrt(mse))

5.74557330725635e-14

In [46]:
y_test = test_set["number of goals team1"].copy()
x_test = test_set.drop("number of goals team1",axis=1)

In [47]:
lr.fit(x_test,y_test)
test_preds = lr.predict(x_test)
mse = mean_squared_error(y_test,test_preds)
print(np.sqrt(mse))

3.071805667454434e-15

In [88]:
df2 = df.loc[df.index==61]
df2.drop(["number of goals team1"], axis = 1, inplace = True)
df2

/var/folders/9b/33w4g3w96gb__9ggs35x898w0000gn/T/ipykernel_2704/672986926.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(["number of goals team1"], axis = 1, inplace = True)

,possession team1,possession team2,possession in contest,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,goal inside the penalty area team2,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
61,34,55,11,0,14,13,0,2,2,0,...,0,0,13,14,0,0,72,47,328,218

In [89]:
predd = lr.predict(df2)
print(predd)

[2.24145127]

,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,total attempts team1,total attempts team2,conceded team1,conceded team2,goal inside the penalty area team1,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
52,35,51,14,1,1,12,16,1,1,1,...,0,0,18,11,0,0,100,100,405,308
58,22,65,13,1,0,9,11,0,1,1,...,0,0,11,10,0,0,88,44,373,165
0,42,50,8,0,2,5,6,2,0,0,...,0,1,6,5,0,0,52,72,256,279
44,46,39,15,0,2,9,12,2,0,0,...,0,0,12,9,0,0,92,84,248,293
5,55,33,12,0,0,11,11,0,0,0,...,0,0,11,11,0,0,76,73,226,287
36,24,60,16,1,0,8,14,0,1,1,...,0,0,14,8,0,0,90,74,341,161
16,51,33,16,0,2,10,21,2,0,0,...,0,0,21,9,0,0,89,84,161,276
12,43,46,11,1,0,8,7,0,1,1,...,0,0,7,8,0,0,64,79,313,316
25,56,32,12,0,2,10,11,2,0,0,...,0,0,11,10,0,0,38,78,194,360
61,34,55,11,2,0,14,13,0,2,2,...,0,0,13,14,0,0,72,47,328,218
56,45,45,10,1,1,9,20,1,1,1,...,0,0,21,9,0,0,95,77,365,423
9,65,22,13,1,2,25,10,2,1,1,...,1,0,12,26,0,0,55,87,164,487
40,43,47,10,0,0,11,15,0,0,0,...,0,0,16,11,0,0,70,68,328,346